package chap15_exception;

import java.util.Scanner;

public class _05_GenerateException {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		
		sc.close();
	}
	
	public static void checkUserIdAndUserPw(String userId, String userPw) {
		String dbUserId = "bit";
		String dbUserPw = "1111";
		
		if(!userId.equals(dbUserId)) {
			// 예외 발생시키기
			// throw new 예외클래스(getMessage 메소드에서 표출할 메시지)
			throw new RuntimeException("id not exist");
		}
		
		if(!userPw.equals(dbUserPw)) {
			throw new RuntimeException("pw not correct");
		}
		
		System.out.println(userId + "님 환영합니다.");
	}
}
