package chap15_exception;

public class _04_Throws {
	public static void main(String[] args) {
		
	}
	
	// throws는 해당 메소드가 호출되는 곳에 예외처리를 위임하는 것이다.
}
